### ISSUE TITLE
What SceneMesher.cs does.

### ISSUE THREAD

**Issue by kat310** [oculus-samples/Unity-Phanto#4]
I didn’t see the PostProcessor scenario in the sample, nor did I see its methods being called and executed by other classes.Is it deprecated?

**Comment by crien-xr** [comment]
SceneMesher executes when running on a Quest 2 or Quest Pro. It generates a low-poly water-tight mesh of the scene as a way to simulate the functionality of the scene mesh available on Quest 3.
