### ISSUE TITLE
Create own scene model export

### ISSUE THREAD

**Issue by PetrSeifert** [oculus-samples/Unity-Phanto#5]
Can I export scene model from my headset to use it as static mesh data?

**Comment by crien-xr** [comment]
This project does not have the functionality to serialize the entire scene model, but you can export the scene mesh as an .obj file.

You will need to attach the `MeshExporter` component (found in Phanto/Utils/Mesh) to the `LobbySceneMeshOverride` or `GameSceneMesh` prefab and assign an export button. When you press that button while the app is running your current scene mesh will get saved to disk. This can be done with a built APK, or while using Quest Link in the editor. The path the file is saved to will be output in the log.

**Comment by mca88** [comment]
Sorry but I'm new to Unity, where should I first place LobbySceneMeshOverride or GameSceneMesh prefabs? In any default Scene? 
Thanks.
