### ISSUE TITLE
can i use other roominfo json file?

### ISSUE THREAD

**Issue by gksthf2845** [oculus-samples/Unity-Phanto#6]
The testroom_ovrscene_export.json file is different in format from the json file extracted by metasimulator DataRecord.apk.
Is there a way to convert or use this?

**Comment by gksthf2845** [comment]
![스크린샷 2024-03-13 181357](https://github.com/oculus-samples/Unity-Phanto/assets/20723721/42e63f86-0f1c-47d4-9301-7307e0feeb90)

**Comment by crien-xr** [comment]
The format used in Phanto is different because we also wanted to include the scene mesh triangles and tracking space details.

It's a good idea to also support the XR Simulator's format. I will add that to our backlog, but no promises on a timeline for that feature. Thanks.

**Comment by gksthf2845** [comment]
fast reply!  thank you ! @crien-xr

can i have way to details record json file data used in phanto ?

**Comment by yoavgoldsteinfb** [comment]
Hello.

For recording scene information, please refer to the documentation provided here: https://developer.oculus.com/documentation/unity/xrsim-scene-recorder/

Overall, [XR Simulator](https://developer.oculus.com/documentation/unity/xrsim-intro/) is a highly recommended tool for working with scene information, and Phanto should be aligned with the exported format
