### ISSUE TITLE
Using Quest3 to enter the application, it shows rescanning and cannot start

### ISSUE THREAD

**Issue by hkshkssfg** [oculus-samples/Unity-Phanto#8]
Unity version: 2022.3.31f1
Device: Mac M2
Quest SDK: v64
I directly packaged the project with Unity and ran it on the device, and it directly prompted me to rescan, but I have already scanned the room data and it can run normally in the first encounter app.
I am a beginner and am confused about this. I look forward to recovery.

**Comment by yoavgoldsteinfb** [comment]
Hello, thanks for posting the issue.
Can you please confirm that you have granted spatial data permission to the app? In addition, which device are you running the app on?
To find the permission settings, in the headset go to `Settings=>Privacy & safety=>App Permissions=>Spatial Data` and make sure the permission is turned on for Phanto

**Comment by hkshkssfg** [comment]
I am using quest 3
I have granted Phanto permission to access spatial data
I found that the Phanto Scene Post Processor script on the prefab Scene Data Loader in the project was lost. I restored it. Is it related to this?
I am not connected to the network. Do I need to connect to the network?



> Hello, thanks for posting the issue. Can you please confirm that you have granted spatial data permission to the app? In addition, which device are you running the app on? To find the permission settings, in the headset go to `Settings=>Privacy & safety=>App Permissions=>Spatial Data` and make sure the permission is turned on for Phanto

**Comment by yoavgoldsteinfb** [comment]
> I found that the Phanto Scene Post Processor script on the prefab Scene Data Loader in the project was lost. I restored it. Is it related to this?

Yes, the `Scene Post Processor` is part of the app flow. It should be restored with the settings as the initial clean clone. Are you building only one scene? or the 3 default scenes?

> I am not connected to the network. Do I need to connect to the network?

No, internet connection is not required

**Comment by hkshkssfg** [comment]
I built 3 default scenes.

> Yes, the `Scene Post Processor` is part of the app flow. It should be restored with the settings as the initial clean clone. Are you building only one scene? or the 3 default scenes?

Is this correct?
<img width="1422" alt="WeChatc5173a3e3009eef8ab0d3bd7564f97fd" src="https://github.com/user-attachments/assets/811b7afb-d537-43e3-94e9-7b8744793670">

**Comment by hkshkssfg** [comment]
I solved the problem by connecting to the internet. Maybe developer mode requires an internet connection?
I don't know, but it does require an internet connection.
Thanks so much for your help!

> No, internet connection is not required

**Comment by hkshkssfg** [comment]
close
