### ISSUE TITLE
Dynamic occlusion no longer works since V68 Meta OS update

### ISSUE THREAD

**Issue by GitHubUsername1** [oculus-samples/Unity-Phanto#9]
Dynamic occlusion no longer works since V68 Meta OS update.
Have updated to Meta Core V67 and Depth API V67 which contain fixes, but Phanto is still referencing old Depth API code.

**Comment by yoavgoldsteinfb** [comment]
Hello. Thanks for reporting the issue. 
We are aware of it and working to fix it as quick as possible.

**Comment by GitHubUsername1** [comment]
> Hello. Thanks for reporting the issue. We are aware of it and working to fix it as quick as possible.

Hi, the latest version of V68 Meta OS has fixed this issue, dynamic occlusion now works again in Phanto. 

Although Phanto still uses the older Meta Core SDK and Depth API versions, with the newer versions the dynamic occlusion is more efficient and looks better, might be considering refactoring the Phanto code that uses these for the improvements. Closing the issue as this is now fixed. Thank you.

**Comment by GitHubUsername1** [comment]
Closed
